/*
 * This source file was generated by the Gradle 'init' task
 */
package com.newardassociates.lispy.app;

public class App {
    public static float version() {
        return 0.1f;
    }

    public static String banner() {
        return "Lispy v" + version();
    }

    public static void main(String[] args) {
        System.out.println(banner());
    }
}
