/*
 * This source file was generated by the Gradle 'init' task
 */
package com.newardassociates.lispy.app;

import org.junit.jupiter.api.Test;

import com.newardassociates.lispy.app.App;

import static org.junit.jupiter.api.Assertions.assertEquals;

class MessageUtilsTest {
    @Test void testVersion() {
        assertEquals(0.1f, App.version());
    }
}
