/*
 * This source file was generated by the Gradle 'init' task
 */
package com.newardassociates.lispy;

import java.util.List;
import java.util.LinkedList;

import org.junit.jupiter.api.Test;

import com.newardassociates.lispy.SExprReader;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class EngineTest {
    @Test void testEvalEmptyProgram() throws java.io.IOException {
        String program = "";
        Object expected = null;

        try (SExprReader reader = new SExprReader(new java.io.StringReader(program))) {
            Object actual = new Engine().eval(reader.parse());
            assertEquals(expected, actual);
        }
    }

    @Test void testEvalAnotherEmptyProgram() throws java.io.IOException {
        String program = "()";
        Object expected = null;

        try (SExprReader reader = new SExprReader(new java.io.StringReader(program))) {
            Object actual = new Engine().eval(reader.parse());
            assertEquals(expected, actual);
        }
    }

    @Test void testEvalYetAnotherEmptyProgram() throws java.io.IOException {
        String program = "(begin)";
        Object expected = null;

        try (SExprReader reader = new SExprReader(new java.io.StringReader(program))) {
            Object actual = new Engine().eval(reader.parse());
            assertEquals(expected, actual);
        }
    }

    /*
    @Test void testIntAtom() {
        String program = "42";
        Atom expected = Atom.of("42");
        Atom actual = Engine.atom(program);
        System.out.println("Actual: " + actual);
        assertEquals(expected, actual);
    }
    @Test void testParseInt() {
        String program = "(42)";
        List<Object> expected = List.of(42);
        List<Object> actual = Engine.parse(program);
        System.out.println("Actual: " + actual);
        assertEquals(expected, actual);
    }

    @Test void testTokenize() {
        String program = "(begin (define r 10) (* pi (* r r)))";
        List<String> expected = List.of(
            "(", "begin", "(", "define", "r", "10", ")", "(", "*", "pi", "(", "*", "r", "r", ")", ")", ")"
        );
        List<String> actual = Engine.tokenize(program);
        assertEquals(expected, actual);
    }
    @Test void testReadFromTokens() {
        List<String> tokens = new LinkedList<>(List.of(
            "(", "begin", "(", "define", "r", "10", ")", "(", "*", "pi", "(", "*", "r", "r", ")", ")", ")"
        ));
        List<Object> expected = List.of(
            "begin",
            List.of("define", "r", "10"),
            List.of("*", "pi", List.of("*", "r", "r"))
        );
        List<Object> actual = Engine.readFromTokens(tokens);
        assertEquals(expected, actual);
    }
    @Test void testParse() {
        String program = "(begin (define r 10) (* pi (* r r)))";
        List<Object> expected = List.of(
            "begin",
            List.of("define", "r", "10"),
            List.of("*", "pi", List.of("*", "r", "r"))
        );
        List<Object> actual = Engine.parse(program);
        assertEquals(expected, actual);
    }
    */
}

