/*
 * This source file was generated by the Gradle 'init' task
 */
package com.newardassociates.lispy;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class EnvTest {
    @Test void testEmpty() {
        Env env = new Env();

        assertEquals(null, env.get("foo"));
    }
    @Test void testScopedEmpty() {
        Env outer = new Env();
        Env env = new Env(outer);

        assertEquals(null, env.get("foo"));
    }
}

