/*
 * This source file was generated by the Gradle 'init' task
 */
package com.newardassociates.lispy;

import java.util.List;

import org.junit.jupiter.api.Test;

import com.newardassociates.lispy.SExprReader;
import static com.newardassociates.lispy.SExprReader.*;
import com.newardassociates.lispy.Env;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/*
 * This needs a TON more tests to be any level of comfortable.
 */

public class SExprReaderTest {
    @Test void testReadExprs() throws java.io.IOException {
        String data =
            "(define name \"ChatGPT\")\n" +
            "(list 1 2 3)\n";

        SExprReader r = new SExprReader(new java.io.StringReader(data));

        SExpr e1 = r.parse();
        assertTrue(e1 instanceof SExprReader.ListExpr);
        ListExpr list1 = (ListExpr)e1;
        assertEquals(3, list1.value.size());
        assertTrue(list1.value.get(0) instanceof SExprReader.Atom);
        assertEquals("define", ((SExprReader.Atom)list1.value.get(0)).value);
        assertTrue(list1.value.get(1) instanceof SExprReader.Atom);
        assertEquals("name", ((SExprReader.Atom)list1.value.get(1)).value);
        assertTrue(list1.value.get(2) instanceof SExprReader.StringLiteral);
        assertEquals("ChatGPT", ((SExprReader.StringLiteral)list1.value.get(2)).value);

        SExpr e2 = r.parse();
        assertTrue(e2 instanceof SExprReader.ListExpr);
        ListExpr list2 = (ListExpr)e2;
        assertEquals(4, list2.value.size());
        assertTrue(list2.value.get(0) instanceof SExprReader.Atom);
        assertEquals("list", ((SExprReader.Atom)list2.value.get(0)).value);
        assertTrue(list2.value.get(1) instanceof SExprReader.Atom);
        assertEquals("1", ((SExprReader.Atom)list2.value.get(1)).value);
        assertTrue(list2.value.get(2) instanceof SExprReader.Atom);
        assertEquals("2", ((SExprReader.Atom)list2.value.get(2)).value);
        assertTrue(list2.value.get(3) instanceof SExprReader.Atom);
        assertEquals("3", ((SExprReader.Atom)list2.value.get(3)).value);
    }

    @Test void testSimpleSchemeProgramTokens() throws java.io.IOException {
        String data =
            "(begin\n" +
            "  (define r 10)\n" +
            "  (* pi (* r r)))\n";

        SExprReader r = new SExprReader(new java.io.StringReader(data));
        SExpr sexpr;
        while ((sexpr = r.parse()) != null) {
            // Just consume for now
            System.out.println("Parsed: " + sexpr.toString());
        }
        
        // Reset for assertions use
        r = new SExprReader(new java.io.StringReader(data));

        SExpr e1 = r.parse();
        assertTrue(e1 instanceof SExprReader.ListExpr);
        ListExpr list1 = (ListExpr)e1;
        assertEquals(3, list1.value.size());
        assertTrue(list1.value.get(0) instanceof SExprReader.Atom);
        assertEquals("begin", ((SExprReader.Atom)list1.value.get(0)).value);
    }

    @Test void testEmptyExprs() throws java.io.IOException {
        String data = "()";
        SExprReader r = new SExprReader(new java.io.StringReader(data));

        SExprReader.SExpr e1 = r.parse();
        assertTrue(e1 instanceof SExprReader.ListExpr);
        assertEquals(0, ((SExprReader.ListExpr)e1).value.size());
        assertEquals(List.of(), ((SExprReader.ListExpr)e1).value);
    }

    @Test void testNotEmptyButActuallyEmptyExprs() throws java.io.IOException {
        String data =
            "   \n" +
            "  ; full line comment\n" +
            "   \n";

        SExprReader r = new SExprReader(new java.io.StringReader(data));

        SExpr e1 = r.parse();
        assertTrue(e1 == null);
    }
    
    @Test void testListNumericExpr() throws java.io.IOException {
        String data = "(42)";
        SExprReader r = new SExprReader(new java.io.StringReader(data));

        SExpr e1 = r.parse();
        assertTrue(e1 instanceof SExprReader.ListExpr);
        ListExpr list = (ListExpr)e1;
        assertEquals(1, list.value.size());
        SExpr e2 = list.value.get(0);
        assertTrue(e2 instanceof SExprReader.Atom);
        assertEquals("42", ((SExprReader.Atom)e2).value);
    }

    @Test void testString() throws java.io.IOException {
        String data = "define";
        SExprReader r = new SExprReader(new java.io.StringReader(data));

        SExpr e1 = r.parse();
        assertTrue(e1 instanceof Atom);
        assertEquals("define", e1.toString());
    }

    @Test void testStringLiteral() throws java.io.IOException {
        String data = "\"d e f\"";
        SExprReader r = new SExprReader(new java.io.StringReader(data));

        SExpr e1 = r.parse();
        assertTrue(e1 instanceof StringLiteral);
        assertEquals("\"d e f\"", e1.toString());
    }

    @Test void testEOFLoop() throws java.io.IOException {
        String program = "(42) (42) (42)";
        SExprReader r = new SExprReader(new java.io.StringReader(program));

        int exprCount = 0;
        SExpr expr = null;
        while ((expr = r.parse()) != null) {
            exprCount++;
        }
        assertEquals(3, exprCount);
    }
}
